### ISSUE TITLE
Action is failing due to probelms with git.io

### ISSUE THREAD

**Issue by beppler** [kevincobain2000/action-gobrew#1]
Since 2023-01-12 git.io is returning HTTP code 503 for the url https://git.io/gobrew used to download the executable.

Maybe this could be changed to https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh, but I do not know the implications.

**Comment by kevincobain2000** [comment]
Oh

**Comment by kevincobain2000** [comment]
now it is no longer 503, may be we can keep it to that for a while

```
╰─$ curl -I https://git.io/gobrew
HTTP/2 302
content-type: text/html;charset=utf-8
location: https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh
```

**Comment by kevincobain2000** [comment]
Will close this, as it seems to be working now.
In the future, if this fails then please update the URL as below https://github.com/kevincobain2000/gobrew/commit/08b42edc86b13048987a1522a4ce96a45cc85391

**Comment by kevincobain2000** [comment]
Added @juev as collaborator on this repo

**Comment by juev** [comment]
I think we should use full url in this action.

[ref](https://github.blog/changelog/2022-04-25-git-io-deprecation/)

> In January 2022, we announced that [git.io was becoming read-only](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/). As notified in January, we shared our plans to deprecate the service. Out of an abundance of caution due to the security of the links redirected with the current git.io infrastructure, we have decided to accelerate the timeline. We will be removing all existing link redirection from git.io on April 29, 2022.
